### ISSUE TITLE
shadho copying files that are already in directory

### ISSUE THREAD

**Issue by tphung3** [jeffkinnison/shadho#20]
**Bug**: shadho attempts to copy work_queue.py to the same location.

**How to Reproduce**: 

1. `conda create shadho-test`                //create a new environment to reproduce this bug
2. `conda activate shadho-test`             //activate this environment
3. `conda install -c conda-forge ndcctools`   //install cctools from conda channel conda-forge
4. `conda install pip`                             //let conda handle pip install
5. `python-m pip install shadho`            //pip install shadho to shadho-test environment
6. `python -m shadho.installers.workqueue --prefix $CONDA_PREFIX`  //"glue" shadho and cctools

**Error**: `Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/t/tphung/anaconda3/envs/shadho-test/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/afs/crc.nd.edu/user/t/tphung/anaconda3/envs/shadho-test/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/afs/crc.nd.edu/user/t/tphung/anaconda3/envs/shadho-test/lib/python3.9/site-packages/shadho/installers/workqueue.py", line 209, in <module>
    main()
  File "/afs/crc.nd.edu/user/t/tphung/anaconda3/envs/shadho-test/lib/python3.9/site-packages/shadho/installers/workqueue.py", line 202, in main
    install_shadho_files(prefix, sp_prefix)
  File "/afs/crc.nd.edu/user/t/tphung/anaconda3/envs/shadho-test/lib/python3.9/site-packages/shadho/installers/workqueue.py", line 176, in install_shadho_files
    shutil.copy(os.path.join(source, 'work_queue.py'), sp_prefix)
  File "/afs/crc.nd.edu/user/t/tphung/anaconda3/envs/shadho-test/lib/python3.9/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/afs/crc.nd.edu/user/t/tphung/anaconda3/envs/shadho-test/lib/python3.9/shutil.py", line 244, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: '/afs/crc.nd.edu/user/t/tphung/anaconda3/envs/shadho-test/lib/python3.9/site-packages/work_queue.py' and '/afs/crc.nd.edu/user/t/tphung/anaconda3/envs/shadho-test/lib/python3.9/site-packages/work_queue.py' are the same file`    

**Temporary Solution**:  commenting out line 176 and 177 in file `https://github.com/jeffkinnison/shadho/blob/master/shadho/installers/workqueue.py` solves the problem.

**Comment by tphung3** [comment]
The issue can be fixed by editing the file `$CONDA_PREFIX/lib/python3.9/shutil.py` and commenting out/removing line 243 and 244 that raise the same file exception. I can't find `shutil.py` in the repo so I can't make a PR however.
